services:
 
  postgres:
    image: postgres:16-alpine
    container_name: taskqueue-postgres
    environment:
      POSTGRES_DB: taskqueue
      POSTGRES_USER: taskqueue
      POSTGRES_PASSWORD: taskqueue
    ports:
      - "5432:5432" # map localhost/server port -> container port
    volumes:
      - postgres_data:/var/lib/postgresql/data #persist data: bind vao localhhost
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskqueue"]
      interval: 5s
      timeout: 5s
      retries: 5
 
  redis:
    image: redis:7-alpine
    container_name: taskqueue-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes    # enable AOF persistence
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
 
volumes:
  postgres_data:
  redis_data: